name: Build
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "::set-output name=dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-      
      - name: Install Dependencies
        run: pnpm install
      - name: ESLint Checks
        run: pnpm lint
  flow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "::set-output name=dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-      
      - name: Install Dependencies
        run: pnpm install
      - name: FlowType Check
        run: pnpm flow
  tsc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "::set-output name=dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-      
      - name: Install Dependencies
        run: pnpm install
      - name: TypeScript type check
        run: pnpm type-check
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
        java-version: [11]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: ${{ matrix.java-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "::set-output name=dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-      
      - name: Install Dependencies
        run: pnpm install
      - name: Install Example Dependencies
        run: cd example && pnpm
      - name: Build android
        run: cd example && pnpm build:android
      - name: Build Android Example App and Library
        run: cd example/android && ./gradlew clean assembleDebug
  ios:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "::set-output name=dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-      
      - name: Install Dependencies
        run: pnpm install      - name: Install Example Dependencies
        run: cd example && pnpm
      - name: Build ios
        run: cd example && pnpm build:ios
      - name: Install Podfiles
        run: cd example && pod install --project-directory=ios
      - name: Build example app
        run: pnpm ios
