name: Windows CI
on: [pull_request]

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [16]

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: 16.5

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "::set-output name=dir::$(pnpm store path)"
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-      
    - name: Install Dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile

    - name: Install example node modules
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: cd example && pnpm

    - name: Build Windows
      run: cd example && pnpm build:windows

    - name: Generate Windows App
      run: cd example && npx install-windows-test-app --use-nuget
     
    # - name: Start Appium server
    #   shell: powershell
    #   run: Start-Process PowerShell -ArgumentList "pnpm appium"
      
    # - name: Run tests
    #   run: pnpm test:windows
